### ISSUE TITLE
Update Action Day Info modal to final copy

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/cmc-biomed-air-quality#15]
We have the copy ready that should go in the Action Day Info modal [here](https://d.pr/i/zgpcaX).

Please replicate the formatting in HTML as seen below. If you find this doesn't fit, feel free to make the modal wider to accommodate.

---

**Air Quality Advisory**

When the number of particles in the air is dangerous to breathe, regional or state agencies issue Air Quality Advisories. 

The Advisory may reflect high levels of:

- ground-level ozone
- particulate matter
- carbon monoxide
- sulfur dioxide
- nitrogen dioxide
- or a combination of these pollutants.

During an Advisory, limit the time you spend outside. Avoid activities that add particles to the air, such as driving and mowing the lawn.

**Comment by rybridge** [comment]
@tnordberg Should the "Air Quality Advisory" text replace the "Action Day Info" heading? Or would that appear below it, just above the rest of the text?

![Mozilla_Firefox](https://github.com/scimusmn/cmc-biomed-air-quality/assets/419370/c84b6d67-fd62-4831-939a-16ac6cfee503)

**Comment by tnordberg** [comment]
@rybridge sorry for not responding earlier to this. I think way you handled this is most likely correct. I will be able to confirm next week with the client.
